dailyaccountstats: Create empty first day on newly created database
The dailyaccountstats management command would fail on a freshly created
database because it was trying to unpack too many values:

  File "/home/gasper/Documents/fedidevs/stats/management/commands/dailyaccountstats.py", line 106, in send_email_report
    today, yesterday = Daily.objects.filter().order_by("-date")[:2]
    ^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

Also fixed account numbers in tests to make more sense.

Signed-off-by: Gasper Martic <martic.gasper@gmail.com>