Accountstats weeks months (#57)
* dailyaccountstats: Create empty first day on newly created database

The dailyaccountstats management command would fail on a freshly created
database because it was trying to unpack too many values:

  File "/home/gasper/Documents/fedidevs/stats/management/commands/dailyaccountstats.py", line 106, in send_email_report
    today, yesterday = Daily.objects.filter().order_by("-date")[:2]
    ^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

Also fixed account numbers in tests to make more sense.

Signed-off-by: Gasper Martic <martic.gasper@gmail.com>

* Start tracking weekly/monthly account change (#16)

Signed-off-by: Gasper Martic <martic.gasper@gmail.com>

* Get correct account stat changes when first creating

Before you would have to run the periodic stats command twice: first
to create the row with all values set to 0 and the second time to
update them with actual values. Moving some code allows us to get the
correct values in the first try.

Signed-off-by: Gasper Martic <martic.gasper@gmail.com>

* dailyaccountstats: Fix bug where account stats were not getting updated

Account stats changes were not getting updated in case one of follower/
following/status counts was not updated when in reality the stats update
should only be skipped if ALL of those counts are the same as before.

Signed-off-by: Gasper Martic <martic.gasper@gmail.com>

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Fix ruff errors

Signed-off-by: Gasper Martic <martic.gasper@gmail.com>

* Ignore silly warning

* Fix ruff errors

* Fix imports

* Calculate weekly and monthly diff every day

---------

Signed-off-by: Gasper Martic <martic.gasper@gmail.com>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: Anže Pečar <anze@pecar.me>